name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: "ubuntu-latest"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.sh
